#ifndef MOTIONBOARDFIRMWARE_PARAMETERS_HPP
#define MOTIONBOARDFIRMWARE_PARAMETERS_HPP
#include <inttypes.h>

constexpr uint16_t MOTOR_CONTROL_LOOP_FREQ = 100; //[Hz]
constexpr float    MOTOR_CONTROL_LOOP_DT   = 1/MOTOR_CONTROL_LOOP_FREQ; //[s]

#endif //MOTIONBOARDFIRMWARE_PARAMETERS_HPP
