COMMONCPPSRC += $(COMMONDIR)/HAL/ports/STM32F303/Logging.cpp
COMMONCPPSRC += $(COMMONDIR)/HAL/ports/STM32F303/Board.cpp
PLATFORMINC += $(CHIBIOS)/os/hal/boards/ST_NUCLEO32_F303K8
PLATFORMINC += $(COMMONDIR)/HAL/ports/STM32F303