COMMONCSRC =

COMMONCPPSRC = $(COMMONDIR)/main.cpp
COMMONCPPSRC += $(COMMONDIR)/MotorControl.cpp
COMMONCPPSRC += $(COMMONDIR)/Shell.cpp
COMMONCPPSRC += $(COMMONDIR)/PID.cpp
COMMONCPPSRC += $(COMMONDIR)/DataStreamer.cpp
COMMONCPPSRC += $(COMMONDIR)/RobotPose.cpp
COMMONCPPSRC += $(COMMONDIR)/Goal.cpp

COMMONINC = $(COMMONDIR)

include $(COMMONDIR)/HAL/hal.mk
