COMMONCSRC =

COMMONCPPSRC = $(COMMONDIR)/main.cpp
COMMONCPPSRC += $(COMMONDIR)/MotorControlLoop.cpp
COMMONCPPSRC += $(COMMONDIR)/Shell.cpp
COMMONCPPSRC += $(COMMONDIR)/PID.cpp
COMMONCPPSRC += $(COMMONDIR)/DataStreamer.cpp
COMMONCPPSRC += $(COMMONDIR)/RobotPose.cpp

COMMONINC = $(COMMONDIR)

include $(COMMONDIR)/HAL/hal.mk
