COMMONCPPSRC += $(COMMONDIR)/HAL/ports/STM32G4/Logging.cpp
COMMONCPPSRC += $(COMMONDIR)/HAL/ports/STM32G4/Board.cpp
PLATFORMINC += $(CHIBIOS)/os/hal/boards/ST_NUCLEO64_G431RB
PLATFORMINC += $(COMMONDIR)/HAL/ports/STM32G4